apiVersion: v1
kind: ServiceAccount
metadata:
  name: judge-api
  namespace: coding-judge
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: judge-worker
  namespace: coding-judge
automountServiceAccountToken: false
